### ISSUE TITLE
Different test behavior using travis-ci

### ISSUE THREAD

**Issue by obr-09** [SpongePowered/McTester#6]
Given three methods working on local (tested on Windows 10 & Linux Mint 18.2), when I try those with travis-ci.org, then one fails without an exception.

[This is the file](https://github.com/OnapleRPG/Harvester/blob/master/src/test/java/com/onaple/harvester/HarvesterTest.java) where the method is called ; its name is testMineAllowedBlock.
The method should place a dirt block, mine it with a diamond shovel and check that the block at the given position is not a block of dirt, but it is.

[Here are the full debug logs](https://api.travis-ci.org/v3/job/412116939/log.txt) (see 16:27:15.282 for the failing method).

I tried adding some delay in case the travis machine didn't have time to execute every commands in time.

**Comment by Aaron1011** [comment]
The issue was that McTester didn't expose any way to wait for a specified number of *client* ticks. The existing `sleepTicks` method only waited for a specified number of *server* ticks - using it provides no guarantee about how many client ticks will have elapsed.

I've added a new method: `Client#sleepTicksClient`, and opened a PR to make Harvester use it: https://github.com/OnapleRPG/Harvester/pull/7
